### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by gorgobacka** [LibreScore/app-librescore#1] opened 2021-11-05 06:56 UTC
Is it possible to provide precompiled versions for Linux or at least provide the steps to install it (using the source)?

**Comment by SealsRock12** [comment] 2021-11-05 21:50
Currently, one of the plugins we use does not have Linux support, but it is planned.

**Comment by pinpox** [comment] 2022-02-02 11:47
Any updates on this? Linux support would be great

**Comment by SealsRock12** [comment] 2022-02-02 16:54
The plugin still doesn't support linux. You can track its development on https://github.com/flutter-webrtc/flutter-webrtc/issues/492, but it doesn't seem like they're making much progress.

**Comment by PeterNjeim** [comment] 2022-02-02 16:54
No updates. We want to have Linux support, as we've said many times in the Discord, the moment one of the plugins we're using supports Linux, well release the Linux version. There's literally nothing we can do right now.

People have had success using Lutris and Wine, at least when not using AMD GPUs: https://discord.com/channels/774491656643674122/774491656643674128/936710744291041291.

**Comment by pinpox** [comment] 2022-02-03 08:54
As I assume the app uses the API, would it be possible to share the necessary request? Maybe Linux Users can work around this with a few curl requests manually until it is fixed.

**Comment by PeterNjeim** [comment] 2022-02-03 08:58
@pinpox if it were that easy, this app wouldn't exist, and the CLI tool would have MSCZ support. We are supporting as many platforms as we can. The app is not compilable on Linux in its current state, please use Wine + Lutris if you aren't on an AMD GPU, otherwise, use an Android emulator or VM, or Windows VM, they work.

**Comment by MeGreen** [comment] 2022-11-21 10:26
Hi, Flutter-webrtc added two releases in the last week regarding linux support, with i guess a more polished 1.0 version being close to finish it seems. It would be awesome, if this app would become supported on linux natively soon :)

**Comment by PeterNjeim** [comment] 2022-11-21 19:10
Thanks for the heads up but we already knew that and made a Linux version already, it'll be releasing soon

**Comment by PeterNjeim** [comment] 2023-01-11 04:23
Soon™ has arrived. I only tested it on Ubuntu 22.04 so you guys need to test it to see if I need to fix anything

Instructions: https://github.com/LibreScore/app-librescore#linux
Download: https://github.com/LibreScore/app-librescore/releases/latest/download/LibreScore.AppImage

[//]: <cc @99thGamer9>

**Comment by PeterNjeim** [comment] 2023-01-11 04:25
cc @Barmarel

**Comment by MeGreen** [comment] 2023-01-11 11:08
Manjaro Gnome with Wayland, fuse2 v2.9.9-4: doesn't install:
```
chmod a+x ./LibreScore.AppImage
./LibreScore.AppImage --install
/tmp/.mount_LibreSNCJ5ld/AppRun: line 7: 11369 Segmentation fault      (core dumped) "${APPDIR}/setup" "$@"
```

**Comment by PeterNjeim** [comment] 2023-01-11 11:10
Well, can't really diagnose it with just a segfault, obviously my first question is, are you using x86_64 or arm64

**Comment by MeGreen** [comment] 2023-01-11 11:11
Sorry, my fault :|
x86_64 64bit, AMD Plattform

Is there a verbose option, or something similar?

**Comment by PeterNjeim** [comment] 2023-01-11 11:14
Well, as the segfault says, there is a core dump. Analyzing a core dump is kind of a tedious task, don't really feel like doing it right now lol, stayed up late today. I'm also on AMD, so that's not the issue. Something I'll ask you to do before I go to bed is to run `./LibreScore.AppImage --appimage-extract`. It'll extract the contents of the appimage into a folder. `AppRun` is the main "initial" binary. Maybe you can skip it and run `librescore` directly (without installing).

**Comment by MeGreen** [comment] 2023-01-11 11:18
´´´
./AppRun
./AppRun: line 12: /librescore: No such file or directory
´´´

Sleep well, i may go poke also a bit

**Comment by MeGreen** [comment] 2023-01-11 11:21
No Stress, thank you for investement.

**Comment by PeterNjeim** [comment] 2023-01-11 11:22
Anyways, you seg faulted while running the `setup` script. It's just a bash script so it's surprising it seg faulted. Try running `./setup --help` and see if it prints the help message. If it does, try running `./setup --install` (it'll probably fail, but it's just to see what's causing the seg fault exactly). This is my last message for today, thanks for debugging for me

**Comment by PeterNjeim** [comment] 2023-01-12 14:26
@MeGreen any updates? Did you try what I shared? I want to know what:
`APPDIR=. ./AppRun`,
`./setup --help`,
`APPDIR=. APPIMAGE="$PWD/AppRun" ./setup --install`,
`APPDIR=. APPIMAGE="$PWD/AppRun" ./setup --uninstall`, and
`LD_LIBRARY_PATH=$LD_LIBRARY_PATH./lib ./librescore` do.

**Comment by Xmader** [comment] 2023-01-12 21:26
Is it possible to build the AppImage on a lower version of Ubuntu? (<= 18.04, maybe in docker since Github Actions has [deprecated the Ubuntu 18.04 runner](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/))

It seems that the segfault comes from the bundled `libc.so.6` (GLIBC_2.35).

**Comment by PeterNjeim** [comment] 2023-01-12 21:49
I can remove the bundled libc and let it use the system version

**Comment by Xmader** [comment] 2023-01-12 21:53
No. 
The minimum version of libc is set to 2.34 during compile time.

```
./librescore: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./librescore)
./librescore: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./lib/libflutter_webrtc_plugin.so)
./librescore: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./lib/libstdc++.so.6)
./librescore: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./lib/libstdc++.so.6)
./librescore: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./lib/libstdc++.so.6)
```

I am using Ubuntu 18.04, and it comes with glibc 2.27.

**Comment by Xmader** [comment] 2023-01-12 22:07
The reason the bundled `libc.so.6` failed is that it isn't using a corresponding `ld-linux.so.2`.
https://stackoverflow.com/a/851229

The path of `ld-linux.so.2` is an absolute path so it didn't get bundled into the AppImage.

`ldd librescore`:
```
...
/lib64/ld-linux-x86-64.so.2 (0x00007fd5e670b000)
...
```
---

I could let it use a relative path by `patchelf --set-interpreter lib/ld-linux-x86-64.so.2 ./librescore`, and 
https://github.com/LibreScore/app-librescore/blob/6d486031790dd4053fc8617ee01954d3f33c0cb0/.github/workflows/build_app.yaml#L67 could bundle it into the AppImage.

The segfault has disappeared but it comes to get a new error that can't display the GUI
```
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast

** (librescore:12277): WARNING **: 17:03:39.349: Failed to start Flutter renderer: Unable to create a GL context


#
# Fatal error in: ../../media/engine/adm_helpers.cc, line 39
# last system error: 0
# Check failed: 0 == adm->Init() (0 vs. -1)
# Failed to initialize the ADM.Aborted
```

[`libstdc++.so` is different from the one used by the OS.](https://askubuntu.com/a/1372874)

**Comment by PeterNjeim** [comment] 2023-01-15 09:41
@MeGreen please try the version `v2.0.48`: https://github.com/LibreScore/app-librescore/releases/download/v2.0.48/LibreScore.AppImage

**Comment by pinpox** [comment] 2023-01-15 15:03
It runs for me, but I can't find anything. This is all I get:
![image](https://user-images.githubusercontent.com/1719781/212548915-877717c7-2205-434b-93a7-3ffda6b06529.png)

Tried searching for `Rush E` or `https://musescore.com/user/30667655/scores/6862109` and both didn't return anything.

**Comment by PeterNjeim** [comment] 2023-01-15 22:12
@pinpox The screenshot you shared is of the downloads tab, so maybe that was a mistake, but I'm sure you meant that no results appear in the home tab. I've seen other people face this issue before, it's therefore not Linux-related and so I won't be helping you in this issue unfortunately. Try the Discord server (found at the top of the README) for support questions

**Comment by pinpox** [comment] 2023-01-16 09:53
Thanks for the clarification. I'll try the Discord, this seems like a (separate) bug though, worth investigating if others are having this as well.

**Comment by MeGreen** [comment] 2023-01-16 10:12
Hi, sry i had a friend over for a few days, and then rehearsal weekend with my orchestra, so i hadn't the time.

Unfortunately version 2.0.48 didn't work for me neither.

with .48 this is the requested outputs:
```
cd squashfs-root

./setup --help
  -h, --help
  -i, --install
  -u, -r, --uninstall, --remove

./setup --install
Error
cp: cannot stat '': No such file or directory
Error

./librescore
./librescore: /mnt/EE7ED4C57ED4882B/Downloads/squashfs-root/lib/libc.so.6: version `GLIBC_2.36' not found (required by /usr/lib/libstdc++.so.6)
```

I've also tried executing everything from my home directory instead of my externally mounted Downloads, but no change there. The same error messages with different paths.

glibc is installed as confirmed by pacman with version 2.36-6

As an inspirations by @Xmader , this is my output of `ldd librescore`

```
ldd librescore
./librescore: MYHDD/Downloads/squashfs-root/./lib/libc.so.6: version `GLIBC_2.36' not found (required by /usr/lib/libstdc++.so.6)
	linux-vdso.so.1 (0x00007ffe7caae000)
	libbitsdojo_window_linux_plugin.so => MYHDD/Downloads/squashfs-root/./lib/libbitsdojo_window_linux_plugin.so (0x00007ffbf59e0000)
	libflutter_webrtc_plugin.so => MYHDD/Downloads/squashfs-root/./lib/libflutter_webrtc_plugin.so (0x00007ffbf5936000)
	liburl_launcher_linux_plugin.so => MYHDD/Downloads/squashfs-root/./lib/liburl_launcher_linux_plugin.so (0x00007ffbf5930000)
	libwindow_size_plugin.so => MYHDD/Downloads/squashfs-root/./lib/libwindow_size_plugin.so (0x00007ffbf5929000)
	libflutter_linux_gtk.so => MYHDD/Downloads/squashfs-root/./lib/libflutter_linux_gtk.so (0x00007ffbf4a00000)
	libgtk-3.so.0 => MYHDD/Downloads/squashfs-root/./lib/libgtk-3.so.0 (0x00007ffbf4000000)
	libgdk-3.so.0 => MYHDD/Downloads/squashfs-root/./lib/libgdk-3.so.0 (0x00007ffbf5814000)
	libpangocairo-1.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libpangocairo-1.0.so.0 (0x00007ffbf49ec000)
	libpango-1.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libpango-1.0.so.0 (0x00007ffbf497e000)
	libharfbuzz.so.0 => MYHDD/Downloads/squashfs-root/./lib/libharfbuzz.so.0 (0x00007ffbf48ab000)
	libatk-1.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libatk-1.0.so.0 (0x00007ffbf487d000)
	libcairo-gobject.so.2 => MYHDD/Downloads/squashfs-root/./lib/libcairo-gobject.so.2 (0x00007ffbf5805000)
	libcairo.so.2 => MYHDD/Downloads/squashfs-root/./lib/libcairo.so.2 (0x00007ffbf3ed2000)
	libgdk_pixbuf-2.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libgdk_pixbuf-2.0.so.0 (0x00007ffbf3e9f000)
	libgio-2.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libgio-2.0.so.0 (0x00007ffbf3cb0000)
	libgobject-2.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libgobject-2.0.so.0 (0x00007ffbf3c4a000)
	libglib-2.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libglib-2.0.so.0 (0x00007ffbf3b02000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007ffbf3800000)
	libm.so.6 => MYHDD/Downloads/squashfs-root/./lib/libm.so.6 (0x00007ffbf3713000)
	libgcc_s.so.1 => MYHDD/Downloads/squashfs-root/./lib/libgcc_s.so.1 (0x00007ffbf3ab2000)
	libc.so.6 => MYHDD/Downloads/squashfs-root/./lib/libc.so.6 (0x00007ffbf3400000)
	libwebrtc.so => MYHDD/Downloads/squashfs-root/./lib/libwebrtc.so (0x00007ffbf2000000)
	libdl.so.2 => MYHDD/Downloads/squashfs-root/./lib/libdl.so.2 (0x00007ffbf4875000)
	libepoxy.so.0 => MYHDD/Downloads/squashfs-root/./lib/libepoxy.so.0 (0x00007ffbf1eac000)
	libpthread.so.0 => MYHDD/Downloads/squashfs-root/./lib/libpthread.so.0 (0x00007ffbf486f000)
	./lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007ffbf59f3000)
	libgmodule-2.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libgmodule-2.0.so.0 (0x00007ffbf4865000)
	libX11.so.6 => MYHDD/Downloads/squashfs-root/./lib/libX11.so.6 (0x00007ffbf1d63000)
	libXi.so.6 => MYHDD/Downloads/squashfs-root/./lib/libXi.so.6 (0x00007ffbf3a9d000)
	libXfixes.so.3 => MYHDD/Downloads/squashfs-root/./lib/libXfixes.so.3 (0x00007ffbf3a94000)
	libatk-bridge-2.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libatk-bridge-2.0.so.0 (0x00007ffbf3a58000)
	libfribidi.so.0 => MYHDD/Downloads/squashfs-root/./lib/libfribidi.so.0 (0x00007ffbf3a3b000)
	libpangoft2-1.0.so.0 => MYHDD/Downloads/squashfs-root/./lib/libpangoft2-1.0.so.0 (0x00007ffbf36f5000)
	libfontconfig.so.1 => MYHDD/Downloads/squashfs-root/./lib/libfontconfig.so.1 (0x00007ffbf36a8000)
	libXinerama.so.1 => MYHDD/Downloads/squashfs-root/./lib/libXinerama.so.1 (0x00007ffbf36a2000)
	libXrandr.so.2 => MYHDD/Downloads/squashfs-root/./lib/libXrandr.so.2 (0x00007ffbf3694000)
	libXcursor.so.1 => MYHDD/Downloads/squashfs-root/./lib/libXcursor.so.1 (0x00007ffbf3687000)
	libXcomposite.so.1 => MYHDD/Downloads/squashfs-root/./lib/libXcomposite.so.1 (0x00007ffbf3681000)
	libXdamage.so.1 => MYHDD/Downloads/squashfs-root/./lib/libXdamage.so.1 (0x00007ffbf367b000)
	libxkbcommon.so.0 => MYHDD/Downloads/squashfs-root/./lib/libxkbcommon.so.0 (0x00007ffbf33b7000)
	libwayland-cursor.so.0 => MYHDD/Downloads/squashfs-root/./lib/libwayland-cursor.so.0 (0x00007ffbf3670000)
	libwayland-egl.so.1 => MYHDD/Downloads/squashfs-root/./lib/libwayland-egl.so.1 (0x00007ffbf366a000)
	libwayland-client.so.0 => MYHDD/Downloads/squashfs-root/./lib/libwayland-client.so.0 (0x00007ffbf3658000)
	libXext.so.6 => MYHDD/Downloads/squashfs-root/./lib/libXext.so.6 (0x00007ffbf3641000)
	libthai.so.0 => MYHDD/Downloads/squashfs-root/./lib/libthai.so.0 (0x00007ffbf3635000)
	libfreetype.so.6 => MYHDD/Downloads/squashfs-root/./lib/libfreetype.so.6 (0x00007ffbf1c99000)
	libgraphite2.so.3 => MYHDD/Downloads/squashfs-root/./lib/libgraphite2.so.3 (0x00007ffbf338f000)
	libpixman-1.so.0 => MYHDD/Downloads/squashfs-root/./lib/libpixman-1.so.0 (0x00007ffbf1bec000)
	libpng16.so.16 => MYHDD/Downloads/squashfs-root/./lib/libpng16.so.16 (0x00007ffbf3351000)
	libxcb-shm.so.0 => MYHDD/Downloads/squashfs-root/./lib/libxcb-shm.so.0 (0x00007ffbf334b000)
	libxcb.so.1 => MYHDD/Downloads/squashfs-root/./lib/libxcb.so.1 (0x00007ffbf331b000)
	libxcb-render.so.0 => MYHDD/Downloads/squashfs-root/./lib/libxcb-render.so.0 (0x00007ffbf3309000)
	libXrender.so.1 => MYHDD/Downloads/squashfs-root/./lib/libXrender.so.1 (0x00007ffbf1bde000)
	libz.so.1 => MYHDD/Downloads/squashfs-root/./lib/libz.so.1 (0x00007ffbf1bc1000)
	libjpeg.so.8 => MYHDD/Downloads/squashfs-root/./lib/libjpeg.so.8 (0x00007ffbf1b3e000)
	libmount.so.1 => MYHDD/Downloads/squashfs-root/./lib/libmount.so.1 (0x00007ffbf1af7000)
	libselinux.so.1 => MYHDD/Downloads/squashfs-root/./lib/libselinux.so.1 (0x00007ffbf1ac8000)
	libffi.so.8 => MYHDD/Downloads/squashfs-root/./lib/libffi.so.8 (0x00007ffbf1aba000)
	libpcre.so.3 => MYHDD/Downloads/squashfs-root/./lib/libpcre.so.3 (0x00007ffbf1a43000)
	libgbm.so.1 => MYHDD/Downloads/squashfs-root/./lib/libgbm.so.1 (0x00007ffbf1a31000)
	libdbus-1.so.3 => MYHDD/Downloads/squashfs-root/./lib/libdbus-1.so.3 (0x00007ffbf19dd000)
	libatspi.so.0 => MYHDD/Downloads/squashfs-root/./lib/libatspi.so.0 (0x00007ffbf199d000)
	libexpat.so.1 => MYHDD/Downloads/squashfs-root/./lib/libexpat.so.1 (0x00007ffbf1969000)
	libuuid.so.1 => MYHDD/Downloads/squashfs-root/./lib/libuuid.so.1 (0x00007ffbf195f000)
	libdatrie.so.1 => MYHDD/Downloads/squashfs-root/./lib/libdatrie.so.1 (0x00007ffbf1955000)
	libbrotlidec.so.1 => MYHDD/Downloads/squashfs-root/./lib/libbrotlidec.so.1 (0x00007ffbf1946000)
	libXau.so.6 => MYHDD/Downloads/squashfs-root/./lib/libXau.so.6 (0x00007ffbf193d000)
	libXdmcp.so.6 => MYHDD/Downloads/squashfs-root/./lib/libXdmcp.so.6 (0x00007ffbf1934000)
	libblkid.so.1 => MYHDD/Downloads/squashfs-root/./lib/libblkid.so.1 (0x00007ffbf18fb000)
	libpcre2-8.so.0 => MYHDD/Downloads/squashfs-root/./lib/libpcre2-8.so.0 (0x00007ffbf1863000)
	libdrm.so.2 => MYHDD/Downloads/squashfs-root/./lib/libdrm.so.2 (0x00007ffbf184b000)
	libwayland-server.so.0 => MYHDD/Downloads/squashfs-root/./lib/libwayland-server.so.0 (0x00007ffbf1831000)
	libsystemd.so.0 => MYHDD/Downloads/squashfs-root/./lib/libsystemd.so.0 (0x00007ffbf1764000)
	libbrotlicommon.so.1 => MYHDD/Downloads/squashfs-root/./lib/libbrotlicommon.so.1 (0x00007ffbf1740000)
	libbsd.so.0 => MYHDD/Downloads/squashfs-root/./lib/libbsd.so.0 (0x00007ffbf1726000)
	liblzma.so.5 => MYHDD/Downloads/squashfs-root/./lib/liblzma.so.5 (0x00007ffbf16f9000)
	libzstd.so.1 => MYHDD/Downloads/squashfs-root/./lib/libzstd.so.1 (0x00007ffbf1623000)
	liblz4.so.1 => MYHDD/Downloads/squashfs-root/./lib/liblz4.so.1 (0x00007ffbf1602000)
	libcap.so.2 => MYHDD/Downloads/squashfs-root/./lib/libcap.so.2 (0x00007ffbf15f6000)
	libgcrypt.so.20 => MYHDD/Downloads/squashfs-root/./lib/libgcrypt.so.20 (0x00007ffbf14b6000)
	libmd.so.0 => MYHDD/Downloads/squashfs-root/./lib/libmd.so.0 (0x00007ffbf14a8000)
	libgpg-error.so.0 => MYHDD/Downloads/squashfs-root/./lib/libgpg-error.so.0 (0x00007ffbf147e000)
```

For their other suggestion, i don't have enough experience with github and building appimages to quickly try them out.

**Comment by PeterNjeim** [comment] 2023-01-16 10:48
@MeGreen I actually deleted the message with the requested commands lol, didn't expect you to still try them. In this case I actually wanted you to just run the AppImage normally, though I can assume that it'll result in the glibc error that you shared

**Comment by MeGreen** [comment] 2023-01-16 11:07
Understandable^^. But normal installation just gives a segfault with the same erorr again, i'm sorry.

**Comment by PeterNjeim** [comment] 2023-01-16 11:17
Is that for `--install`? How about running the AppImage without any flags, just `./LibreScore.AppImage`

**Comment by MeGreen** [comment] 2023-01-16 11:18
Yes, that's for `--install`. Just running gives
```
./librescore: /tmp/.mount_LibreStUEW8h/lib/libc.so.6: version `GLIBC_2.36' not found (required by /usr/lib/libstdc++.so.6)
```

**Comment by PeterNjeim** [comment] 2023-01-20 02:47
@MeGreen @Xmader @gorgobacka @99thGamer9 @Barmarel Please try version `v2.0.49`: https://github.com/LibreScore/app-librescore/releases/download/v2.0.49/LibreScore.AppImage

**Comment by Xmader** [comment] 2023-01-20 16:33
It gives
```
/tmp/.mount_LibreSYf09Fi/AppRun: line 7:  7759 Segmentation fault      ldconfig -p
      7760                       | grep libstdc++
      7761                       | awk '{ system("echo " $4) }'
      7762                       | head -n 1
      7763                       | xargs -I {} strings {}
      7764                       | grep GLIBC_"[[:digit:]]"
      7765                       | sort -V
      7766                       | tail -n 1
      7767                       | cut -c 7-
/tmp/.mount_LibreSYf09Fi/AppRun: line 7:  7757 Exit 139                { ldconfig -p | grep libstdc++ | awk '{ system("echo " $4) }' | head -n 1 | xargs -I {} strings {} | grep GLIBC_"[[:digit:]]" | sort -V | tail -n 1 | cut -c 7- && ldd "${APPDIR}/librescore" | grep libstdc++ | awk '{ system("echo " $3) }' | head -n 1 | xargs -I {} strings {} | grep GLIBC_"[[:digit:]]" | sort -V | tail -n 1 | cut -c 7-; }
      7758 Segmentation fault      | sort -C -V
/tmp/.mount_LibreSYf09Fi/AppRun: line 12: /tmp/.mount_LibreSYf09Fi/librescore: No such file or directory
```

**Comment by Xmader** [comment] 2023-01-20 17:01
It seems that `ldd "${APPDIR}/librescore"` gives out `Segmentation fault` because of using bundled libraries by  
 `export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}${APPDIR}/lib"`

**Comment by MeGreen** [comment] 2023-01-20 19:22
Yeah unfortunately it's still the same X| I'm really so sorry!

**Comment by MeGreen** [comment] 2023-01-20 19:24
Is there any way to check if it's just the appimage bundling, and not the program itself, so it may be packaged as a snap/flatpak as an alternativ? I'm not into development, i just know that these are two more very popular packaging formats for distro-agnostic packages.

**Comment by Xmader** [comment] 2023-01-20 19:41
I think I've solved the MESA-LOADER error. 

By add the `LIBGL_DEBUG=verbose`  environment variable (`export LIBGL_DEBUG=verbose`),
it gives out a more verbose reason of why libGL has failed to load driver
```
libGL: MESA-LOADER: failed to open /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: <some_path>/squashfs-root/lib/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /lib/x86_64-linux-gnu/librt.so.1)
libGL: MESA-LOADER: failed to open \$${ORIGIN}/dri/swrast_dri.so: \$${ORIGIN}/dri/swrast_dri.so: cannot open shared object file: No such file or directory
libGL: MESA-LOADER: failed to open /usr/lib/dri/swrast_dri.so: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast

** (librescore:7975): WARNING **: 14:25:55.611: Failed to start Flutter renderer: Unable to create a GL context


#
# Fatal error in: ../../media/engine/adm_helpers.cc, line 39
# last system error: 0
# Check failed: 0 == adm->Init() (0 vs. -1)
# Failed to initialize the ADM.Aborted
```

It turns out the program is still using the system `librt.so.1`.

Then I copied [glibc2.35](https://mirrors.kernel.org/ubuntu/pool/main/g/glibc/libc6_2.35-0ubuntu3_amd64.deb)'s `lib/x86_64-linux-gnu/librt.so.1` into `squashfs-root/lib/`, everything runs perfectly.

**Comment by PeterNjeim** [comment] 2023-01-20 20:18
@MeGreen please extract the AppImage with `--appimage-extract`, and cd into the `squashfs-root` directory, and share the outputs of:

`ldconfig -p | grep libstdc++ | awk '{ system("echo " $4) }' | head -n 1 | xargs -I {} strings {} | grep GLIBC_"[[:digit:]]" | sort -V | tail -n 1 | cut -c 7-`

`APPDIR=$PWD ldd "${APPDIR}/librescore" | grep libstdc++ | awk '{ system("echo " $3) }' | head -n 1 | xargs -I {} strings {} | grep GLIBC_"[[:digit:]]" | sort -V | tail -n 1 | cut -c 7-`

`APPDIR=$PWD cd "${APPDIR}/lib" && LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${APPDIR}/lib" "${APPDIR}/librescore" "$@"`

(`cd ..` to get back into the squashfs-root directory before running:)
`APPDIR=$PWD cd $(dirname $(ldd "${APPDIR}/librescore" | grep ld-linux | awk '{ system("echo " $3) }' | head -n 1)) && LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${APPDIR}/lib" LD_PRELOAD="$(ldconfig -p | grep libstdc++ | awk '{ system("echo " $4) }' | head -n 1):$(ldconfig -p | grep libm\\. | awk '{ system("echo " $8) }' | head -n 1):$(ldconfig -p | grep libc\\. | awk '{ system("echo " $8) }' | head -n 1)" "${APPDIR}/librescore" "$@"`

**Comment by MeGreen** [comment] 2023-01-20 20:46
```
cd squashfs-root

ldconfig -p | grep libstdc++ | awk '{ system("echo " $4) }' | head -n 1 | xargs -I {} strings {} | grep GLIBC_"[[:digit:]]" | sort -V | tail -n 1 | cut -c 7-
cpy_chk@GLIBC_2.4

APPDIR=$PWD ldd "${APPDIR}/librescore" | grep libstdc++ | awk '{ system("echo " $3) }' | head -n 1 | xargs -I {} strings {} | grep GLIBC_"[[:digit:]]" | sort -V | tail -n 1 | cut -c 7-
ldd: /librescore: No such file or directory     # additional output of zsh regarding command execution = 1|1|0|0|0|1|0|0|0 ✔ 

APPDIR=$PWD cd "${APPDIR}/lib" && LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${APPDIR}/lib" "${APPDIR}/librescore" "$@"
zsh: no such file or directory: /librescore

APPDIR=$PWD cd $(dirname $(ldd "${APPDIR}/librescore" | grep ld-linux | awk '{ system("echo " $3) }' | head -n 1)) && LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${APPDIR}/lib" LD_PRELOAD="$(ldconfig -p | grep libstdc++ | awk '{ system("echo " $4) }' | head -n 1):$(ldconfig -p | grep libm\\. | awk '{ system("echo " $8) }' | head -n 1):$(ldconfig -p | grep libc\\. | awk '{ system("echo " $8) }' | head -n 1)" "${APPDIR}/librescore" "$@"
ldd: /librescore: No such file or directory
dirname: missing operand
Try 'dirname --help' for more information.
zsh: no such file or directory: /librescore
```

hope it helps

**Comment by PeterNjeim** [comment] 2023-01-20 20:46
@MeGreen don't waste your time with what I sent you earlier, I'm going to release `v2.0.52` shortly and you can test that one

**Comment by MeGreen** [comment] 2023-01-20 20:46
hahahaha too late :D

**Comment by PeterNjeim** [comment] 2023-01-20 20:47
holy moly you posted it in the same second

**Comment by PeterNjeim** [comment] 2023-01-20 20:48
And by shortly I mean 12 minutes

**Comment by PeterNjeim** [comment] 2023-01-20 21:01
@MeGreen @gorgobacka @99thGamer9 @Barmarel Please try version v2.0.52: https://github.com/LibreScore/app-librescore/releases/download/v2.0.52/LibreScore.AppImage

**Comment by MeGreen** [comment] 2023-01-20 21:08
Sadly no change. I've also followed your previous instructions, the output is exactly the same. I've also made sure, that i've tried the right version. Seems to me, that it has a bit of a problem to assign the right folders to the variables?

**Comment by PeterNjeim** [comment] 2023-01-20 21:10
There isn't a folder named librescore, something's wrong with your linux installation. `echo $PWD` should show your current directory, but in this case it's empty

**Comment by MeGreen** [comment] 2023-01-20 21:11
Okay, i'm using zsh, i will try again with bash. Maybe that it's. In the meantime, i've also tried it on my laptop, same distro+DE, but same there.

**Comment by PeterNjeim** [comment] 2023-01-20 21:11
I use `zsh`, that's not the problem

**Comment by PeterNjeim** [comment] 2023-01-20 21:12
You said the same thing's happening but so much has happened that I don't really know what exactly is happening. Please share the output of `./LibreScore.AppImage`

**Comment by Xmader** [comment] 2023-01-20 21:13
Instead of prepending `APPDIR=$PWD`, I think you should run `APPDIR=$PWD` in a separate command

**Comment by MeGreen** [comment] 2023-01-20 21:14
oh shit it's doing something

```
./LibreScore.AppImage

(librescore:27420): Gtk-WARNING **: 22:12:55.865: Error loading icon from file '/tmp/.mount_LibreSia7cxS/data/flutter_assets/assets/librescore-square.svg':
	Couldn’t recognise the image file format for file “/tmp/.mount_LibreSia7cxS/data/flutter_assets/assets/librescore-square.svg”
libEGL warning: MESA-LOADER: failed to open radeonsi: /tmp/.mount_LibreSia7cxS/lib/libc.so.6: version `GLIBC_2.36' not found (required by /usr/lib/libLLVM-14.so) (search paths /usr/lib/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: /tmp/.mount_LibreSia7cxS/lib/libc.so.6: version `GLIBC_2.36' not found (required by /usr/lib/libLLVM-14.so) (search paths /usr/lib/dri, suffix _dri)


** (librescore:27420): WARNING **: 22:12:56.002: Failed to start Flutter renderer: No GL implementation is available

```

![Screenshot from 2023-01-20 22-13-19](https://user-images.githubusercontent.com/24845687/213806531-1380292b-7dcc-4d68-9711-c2dedeff8c28.png)

**Comment by PeterNjeim** [comment] 2023-01-20 21:14
Let me be clear here, those commands I gave you earlier, I already said you don't need to do them anymore, they aren't necessary anymore. I don't use $PWD in the new version nor in the older versions, that was just for you to test those specific commands

**Comment by MeGreen** [comment] 2023-01-20 21:15
Ah, okay sorry, yeah that was what i meant with "same"

**Comment by PeterNjeim** [comment] 2023-01-20 21:18
Please try this custom version: https://gofile.io/d/gxn37X

**Comment by MeGreen** [comment] 2023-01-20 21:22
Progress! `./LibreScore.AppImage`

![Screenshot from 2023-01-20 22-19-22](https://user-images.githubusercontent.com/24845687/213807309-10c020dc-f219-49f7-9e21-e91121d6ec00.png)

It looks and feels good, it just throws a network error on every action now. But i think you already mentioned that that may be something else.

Also now:
```
./LibreScore.AppImage --install
Error
```

**Comment by PeterNjeim** [comment] 2023-01-20 22:21
@MeGreen try version `v2.0.54`: https://github.com/LibreScore/app-librescore/releases/download/v2.0.54/LibreScore.AppImage. It won't fix the error but it'll tell you what's wrong

**Comment by MeGreen** [comment] 2023-01-20 22:23
Thank you very much for investing your time into this!

```
./LibreScore.AppImage --install
gtk-update-icon-cache: The generated cache was invalid.
```

**Comment by PeterNjeim** [comment] 2023-01-20 22:27
Try this:
```bash
sudo touch /usr/share/icons/hicolor ~/.local/share/icons/hicolor
sudo gtk-update-icon-cache
```

**Comment by MeGreen** [comment] 2023-01-20 22:35
I've skipped the `touch` as i first checked if these folder already exist, and indeed they do, and are happily populated.

I've did the icon cache update, the error persists.
Upon running `LibreScore.AppImage --install` it creates a file called ".icon-theme.cache" in ~/.local/share/icons/hicolor, as observed by my file browser regenerating a thumbnail for it, and the "created" time stamp of that file.

**Comment by PeterNjeim** [comment] 2023-01-20 22:36
The touch is to update the folder's timestamp, please run it

**Comment by MeGreen** [comment] 2023-01-20 22:38
Okay, did it, then updated the icon cache and tried `--install` but fails again with invalid icon cache.

**Comment by PeterNjeim** [comment] 2023-01-20 22:43
I don't really know the issue, I don't think it's a LibreScore one, as it runs fine for me. You can look up the error and see if you can solve it. But anyways, I'll release a new version that doesn't exit the installer upon hitting an error

**Closed** 2023-01-20 22:59 UTC
Labels: enhancement

**Comment by PeterNjeim** [comment] 2023-01-20 23:31
@MeGreen installation on the newest version should work now despite the error, you can check if it worked by running `librescore`

**Comment by MeGreen** [comment] 2023-01-21 11:03
Oh yeah! It worked just fine, installed perfectly and integrated just fine (created a .desktop entry). Can also confirm that downloading works.

Would you care to elaborate what the error was in the end, if it's not too much to ask?
