### ISSUE TITLE
Add score viewing

### ISSUE THREAD

**Issue by icarusinthewings** [LibreScore/app-librescore#17] opened 2022-08-05 18:10 UTC
On mobile, there is no way to open scores for free except for through the proprietary web interface. This app would be awesome with that feature.

**Comment by PeterNjeim** [comment] 2022-08-07 23:20
Duplicate of #16

**Closed by PeterNjeim** 2022-08-07 23:20 UTC
Labels: duplicate

**Comment by PeterNjeim** [comment] 2022-08-07 23:30
If you're asking about making an interface similar to the MuseScore mobile app, where you can play the music and rewind etc. while also seeing what note is currently being played in the sheet itself, that's too big of an undertaking for me, and would be better served by people who actually develop MuseScore. You can ask on their GitHub if they can develop a viewer for MSCZ files on mobile, however I personally don't think it would be that useful.

Also please note that I have stopped working on this project, I only maintain it by updating dependencies and making sure new translations aren't vandalous, etc. New features are no longer being worked on.
